- hosts: webservers
  gather_facts: true
  become: true

  roles:
    - role: letsencrypt
      vars:
        letsencrypt_email: ahmadfarman1701@gmail.com
        main_domain_name: sosialmedia.dailybugis.my.id
        all_domain_names:
            - sosialmedia.dailybugis.my.id
       
        deploy_sample_html: true
